name: kubeflow-mnist
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6.6
    - pip=20.0.2
    - pip:
        - tensorflow-gpu==1.14
        - kfp==1.0.0
        - kubernetes==10.0.1
        - kfserving==0.4.0